name: Compile TypeScript

on:
  pull_request:
    branches: main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository’s code

      - name: Debug file locations (After Checkout)
        run: |
          echo "Listing all files in the repository after checkout:"
          ls -R  # List all files in the repository
          pwd  # Show current working directory

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Specify Node version

      - name: Initialize npm and create package.json
        run: |
          npm init -y  # Automatically generate package.json with default values

      - name: Install TypeScript and dependencies
        run: |
          npm install typescript --save-dev  # Install TypeScript
          echo "Installed dependencies:"
          cat package.json  # Show the content of package.json

      - name: Debug file locations (After Install)
        run: |
          echo "Verifying repository contents before compiling:"
          ls -R  # List all files to ensure TypeScript files are in place

      - name: Compile TypeScript files
        run: |
          npx tsc --pretty --noEmit --listFiles  # Compile with detailed logs

      - name: List all JavaScript files
        run: |
          find . -name "*.js"  # Print all .js files in the repository
