name: Manual Workflow Test

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  install-run:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0  # Use the specific version (v4.2.0) of setup-node

      - name: Confirm Node.js Installation
        run: node -v  # Prints the Node.js version to confirm it is installed

      - name: Install TypeScript
        run: npm install -g typescript  # Installs TypeScript globally

      - name: Confirm TypeScript Installation
        run: tsc --version  # Prints the TypeScript version to confirm it is installed

  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out the repository’s code

      - name: List files in the repository
        run: |
          echo "Listing files in the repository..."
          ls -R  # List all files recursively
    
