name: Compile TypeScript

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository’s code

      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository"
          ls -R  # List all files in the repository

  install:
    runs-on: ubuntu-latest
    needs: checkout  # This job depends on the checkout job
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Specify Node version

      - name: Initialize npm and create package.json
        run: |
          npm init -y  # Automatically generate package.json with default values

      - name: Install TypeScript
        run: |
          npm install typescript --save-dev  # Add TypeScript as a dev dependency

      - name: Add build script to package.json
        run: |
          jq '.scripts.build = "tsc"' package.json > temp.json && mv temp.json package.json  # Add the "build" script to package.json

      - name: Install dependencies
        run: |
          npm install  # Install dependencies from the dynamically created package.json

  compile:
    runs-on: ubuntu-latest
    needs: [checkout, install]  # Compile job depends on both checkout and install jobs    
    steps:
      - name: Debug file locations
        run: |
          echo "Verifying repository contents before compiling:"
          ls -R  # List all files to ensure TypeScript files are in place
                
      - name: List TypeScript files
        run: |
          find . -name "*.ts"  # List all .ts files to ensure they exist

      - name: Compile TypeScript files
        run: |
          npx tsc --project tsconfig.json --pretty --noEmit # Explicitly specify the tsconfig.json
          
      - name: List all JavaScript files
        run: |
          find . -name "*.js"  # Print all .js files in the repository
