name: Manual Workflow Test

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  confirm-run:
    runs-on: ubuntu-latest

    steps:
      - name: Confirm Run
        run: echo "The workflow ran successfully on the setting-up-tests-branch!"