name: Compile TypeScript

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository’s code

      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository"
          ls -R  # List all files in the repository

  install:
    runs-on: ubuntu-latest
    needs: checkout  # This job depends on the checkout job
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # Specify Node version

      - name: Initialize npm and create package.json
        run: |
          npm init -y  # Automatically generate package.json with default values

      - name: Install dependencies
        run: |
          npm install  # Install dependencies from the dynamically created package.json

  compile:
    runs-on: ubuntu-latest
    needs: [checkout, install]  # Compile job depends on both checkout and install jobs
    steps:
      - name: Compile TypeScript files
        run: |
          npx tsc --pretty --noEmit  # This checks for TypeScript errors without emitting the files
          
      - name: List all JavaScript files
        run: |
          find . -name "*.js"  # Print all .js files in the repository
