name: Compile TypeScript

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository’s code

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify Node version

      - name: Install dependencies
        run: |
          npm install  # Install dependencies

  compile:
    runs-on: ubuntu-latest
    needs: [checkout, install]  # Compile job depends on both checkout and install jobs
    steps:
      - name: Compile TypeScript files
        run: |
          npx tsc  # Run TypeScript compiler (tsc) to compile .ts files into .js
          
      - name: List all JavaScript files
        run: |
          find . -name "*.js"  # Print all .js files in the repository       
